language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install
  - pip install coveralls
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - coverage run --source=api -m pytest && coverage report

after_script:
  - coveralls
  